### ISSUE TITLE
Dogs: potential duplicated VBO terms in v2023-06-01 

### ISSUE THREAD

**Issue by rando2** [monarch-initiative/vertebrate-breed-ontology#106]
Hi all,
I'm using some of the dog breed ontology and noticed a couple of things I wanted to double-check are intentional:

VBO:0200236 is British Bulldog 
British Bulldog is also a synonym for VBO:0200258 (Bulldog). To the best of my knowledge, this is correct, it's just an alternate name.

VBO:0201029 most common name is "Pointer" but it includes English Pointer as an alternate name. Most of the other alternate names are something along the lines of "pointer - unspecified" or "pointer- other"
English pointer is VBO:0200494 and does not include "pointer" as an alternate name.

VBO:0200298 is Catahoula Leopard Dog, but Catahoula Leopard Dog is also listed as an alternate term for VBO:0200820, Leopard Cur (Dog). 
Louisiana Catahoula is listed as an alternate term for VBO:0200298 (Catahoula Leopard Dog), but it is also its own VBO term (VBO:0200835: Louisiana Catahoula Leopard Dog).

I know I haven't been at the last few meetings, so I figured I should mention this somewhere in case it's helpful!

**Comment by franknic** [comment]
Thank you, Haile
I agree that British Bulldog VBO:0200236 is a synonym for Bulldog VBO: 0200258. VBO lists only VeNom as a source for British Bulldog, and, so far as I can see, the various registering organisations list only Bulldog and do not have British Bulldog as a breed.
I also agree that English pointer VBO:0200494 is a synonym of Pointer VBO:0201029. For example, the (English) Kennel Club lists only "Pointer" and not "English Pointer", but the latter is very commonly used as a synonym of "Pointer". Confusingly, the official name for "Pointer" in FCI is "English Pointer". But I still think it would be best to follow the English guide and list English Pointer as a synonym of Pointer.
The last issue needs someone with specialist knowledge to resolve.
This raises an important point, namely that we now really have reached the point where VBO needs a team of advisors who are very knowledgeable about breeds in particular species. My advice above is not from first-hand experience, and needs to be checked, which all takes time. People such as Leslie Lyons (cats) and Claire Wade (dogs) have that specialist knowledge or could suggest suitable specialists if they do not have the time. And we could find similar specialists for other species. The sooner we can assemble a team of such advisors, the better! And this will have additional benefits for VBO, because we will then have the active support of people with specialist knowledge of breeds.

**Comment by katiermullen** [comment]
See issue #150 for strategy to obsolete dog breed duplicates.
