### ISSUE TITLE
Add LBO database cross references

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/vertebrate-breed-ontology#128]
Hi @franknic and @ImkeTammen,

I am wondering if I can request your help adding LBO database cross references for livestock breeds in VBO?

Imke and I have already done some mapping of terms, but there are about 643 LBO terms that are not mapped to existing VBO terms. If these LBO terms represent unique concepts, we will add them to VBO as new terms. But, before doing that I am hoping you can help me make sure that they are indeed unique terms.  

I have created a spreadsheet to use for this [here](https://docs.google.com/spreadsheets/d/1NUmtj2DjKcRgoVr-vEr57MSp19N8V0nywT1wUYXn7ro/edit#gid=1404897259).

The instructions are in the Read Me tab:

- I have only included the LBO terms that have not yet been mapped to VBO terms because they do not have an exact match or were not manually curated by Imke (cattle breeds).
- LBO terms can only be mapped to VBO transboundary terms (not country-breed terms as these are reserved for DAD-IS only).
- A LBO term can only be mapped to 1 VBO term, if you think a LBO term maps to multiple VBO terms, please flag this in yellow.
- Enter the LBO Preferred Label, LBO Species, LBO ID and your ORCID in columns E-H of the worksheet labeled "Update DADIS Transboundary".

@sabrinatoro will make sure that we can use the "LBO:" prefix in VBO.

Thank you!!!

**Comment by katiermullen** [comment]
@ImkeTammen thank you and your student for your help. If your student has a ORCID, please have her use to identify the LBO-VBO matches that she makes so that we can acknowledge her contributions.

**Comment by franknic** [comment]
Thank you, all, for your efforts on this. It seems to be in good hands. If I can help, please let me know.

**Comment by katiermullen** [comment]
@franknic @ImkeTammen @nsaklou -

@sabrinatoro and I are working on creating a sync pipeline for LBO terms to be added to VBO. To start, we are mapping LBO terms to existing VBO terms using the matches that @ImkeTammen has made as well as some additional terms that I have mapped. See: [https://docs.google.com/spreadsheets/d/1MxZrRYooKGS-1OHt75i_WR4y_uE_lW3yHCRyWAGOW3Q/edit#gid=0](url). 

LBO terms that do not exist in VBO will added as new terms. This is where we need your help. If you see any LBO terms in this list [https://docs.google.com/spreadsheets/d/1MxZrRYooKGS-1OHt75i_WR4y_uE_lW3yHCRyWAGOW3Q/edit#gid=2052501147](url) that match existing VBO terms, please fill in the VBO ID, VBO name and your ORCID in the yellow highlighted columns. 

Some notes -
- The LBO terms and VBO terms should match 1:1. If you find a case where an LBO term maps to more than one VBO term, or a VBO term maps to more than one LBO term, please highlight this. 
- LBO terms should only map to VBO transboundary terms since LBO terms are not defined by country.

Please let me know if you have any questions or concerns. Thank you for your help!

**Comment by franknic** [comment]
Thank you very much, Katie and Sabrina.
It seems we have quite a task ahead of us: if I understand correctly, there are 472 matches and 641 that don't match.  Imke and I will discuss this as soon as possible, and will give this high priority.
Since the LBO list comprises breeds that occur in more than one country _and_ breeds that occur in just one country, I suspect that we will be able to find quite a number of matches by looking at breed-country entries where the breed name occurs in only one country, i.e breed-country entries with parent = species. I have just done this for the 133 unmatched LBO cattle breeds, and have achieved 60 matches with VBO breeds. Obviously I will have to check these, but that provisional result is encouraging.
Two questions come to mind:
1. Have you been in touch with Zhiliang and Cari about this?
2. If my sums are correct, the total of the matched and unmatched entries is 1,113, compared with the total of 1,124 entries in v9.3, which is in sheet "LBO source data". Have I misunderstood something?

**Comment by katiermullen** [comment]
@franknic - thank you so much for your help! 

To answer your questions:

1. We will certainly show the results to Zhiliang and Cari for comment once we have them.
2. The last 12 rows of "LBO source data" are high level classification terms and obsoleted terms, perhaps this is causing the discrepancy?

**Comment by franknic** [comment]
Thank you very much, Katie
A progress report: I've been giving this job top priority. So far, I've managed to match 497 and have 23 recommendations for new entries, each with a reference, in most cases Mason's dictionary, which is proving to contain a wealth of information. That leaves 121 still to be done. I'll submit a first round of results early next week, as there are some of the remaining unmatched entries that will require quite a lot of time to work out.

**Comment by franknic** [comment]
Back again, having just finished transferring my matches to the Goole docs sheet [Test LBO](https://docs.google.com/spreadsheets/d/1MxZrRYooKGS-1OHt75i_WR4y_uE_lW3yHCRyWAGOW3Q/edit#gid=2052501147)
I have added six columns. The first four are for cases where an LBO entry matches with more than one VBO entry. These are cases where a breed exists in more than one country but where DADIS has not created a transboundary entry.
The other two columns are for additional synonyms to be added to the VBO entry. The first of these columns comprise the LBO names for a breed, where the LBO name differs from the VBO name, and is not yet a synonym. The second column contains a small number of additional suggestions that I encountered while doing the matching.
I hope this is helpful
I will keep working at the remaining entries

**Comment by franknic** [comment]
One other thing, Katie. It is possible that I inadvertently replaced one of your entries with one from my list, while I was getting used to the google doc speadsheet. It would have been near to the top, possibly in buffalo.  I hope this didn't happen, but please check. And if it has been replaced, please check that the new version is OK.
Once I got used to the Google docs sheet, I managed to retain all your other entries. For some of them, I added synonym suggestions where the LBO breed name was different from the VBO name and the LBO name was not yet a synonym in VBO.

**Comment by katiermullen** [comment]
@franknic Thank you for your hard work on this! I very much appreciate this and your work will definitely help us move forward!

**Comment by franknic** [comment]
Another progress report. I have now managed to map 554 of the 641 LBO entries. 79 of the remaining unmatched entries will each require a new entry, and almost all of these can be referenced to Mason's dictionary. That leaves just 8 entries still to be matched. I'll load the remaining matched entries tonight, and will begin assembling a list of suggested new entries with relevant sources.

**Comment by katiermullen** [comment]
@franknic I made this [spreadsheet ](https://docs.google.com/spreadsheets/d/1MxZrRYooKGS-1OHt75i_WR4y_uE_lW3yHCRyWAGOW3Q/edit#gid=2071224812) called "New Term Additions" from the terms in "LBO terms without VBO matches" that do not have a VBO ID associated with them. There are a total of 110 terms in this new sheet. I added some columns in yellow for you to add info from Mason or other sources as you see fit. Please let me know if this suits your needs or if I can edit the sheet in any way to make it easier for you to use.

**Comment by franknic** [comment]
Thank you very much, Katie. Some of those 110 comprise matches that I still have to add to the other sheet, but most of them will be new. Your columns seem fine, and will make my task far easier. I will report back as soon as I have made some progress.

**Comment by franknic** [comment]
Greetings, Katie
I've just completed all the matchings in [Test LBO](https://docs.google.com/spreadsheets/d/1MxZrRYooKGS-1OHt75i_WR4y_uE_lW3yHCRyWAGOW3Q/edit#gid=2052501147). Tomorrow I shall start adding new entries in the [new spreadsheet](https://docs.google.com/spreadsheets/d/1MxZrRYooKGS-1OHt75i_WR4y_uE_lW3yHCRyWAGOW3Q/edit#gid=2071224812).

**Comment by katiermullen** [comment]
Thank you @franknic!

**Comment by franknic** [comment]
Thank you, Katie! As so often happens, I was over-optimistic on my timeline, but the new entries will appear as soon as possible.
Also, in looking at the small number of unresolved cases, I was able to actually match one, which has now been included in the matching sheet:



Cattle LBO:0000067 Canary Island is matched with VBO:0004710 Canaria, Spain (Cattle). I am assuming that Nico's magic code will include the LBO name "Canary Island" as a synonym in VBO.

**Comment by katiermullen** [comment]
Thank you @franknic. I appreciate your dedication to this time consuming task. I will be in the clinic next week and may be slow to respond, but please let me know if you run into any roadblocks.

**Comment by franknic** [comment]
Back again, having now entered the first two new entries.
I, too, will be otherwise engaged this coming week, but I thought it may be helpful for me to report back now.
For both entries and (I suspect) for most other entries, both the Mason Dictionary and the Mason Encyclopedia are valuable sources. 
1. Is it possible for me to include two ISBNs as a source? (For now, I have entered only the dictionary ISBN)
2. I have page numbers for the dictionary and the encyclopedia entries. Am I correct in recalling that it is not feasible to include these?
3. For the first entry (Allmogekor, cattle), the three synonyms entered into the spreadsheet actually correspond to three VBO breed-country entries, namely Väneko, Sweden (Cattle) VBO:0005283, Bohuskulla, Sweden (Cattle) VBO:0005273, Ringamålako, Sweden (Cattle) VBO:0005276. Is it possible for this information to be included?

**Comment by katiermullen** [comment]
@franknic -  

1. Yes, you can include two ISBNs as a source. Please separate them with a "|" with no spaces.
2. We cannot include page numbers.
3. Are you saying that Allmogekor (Cattle) should be the parent for breed country-terms Väneko, Sweden (Cattle) VBO:0005283, Bohuskulla, Sweden (Cattle) VBO:0005273, Ringamålako, Sweden (Cattle) VBO:0005276? If so, yes, we can include that information. 

Thank you so much for your help!

**Comment by franknic** [comment]
Thank you, Katie
I've now done 640 of the 641 LBO entries! The only remaining one is Meijiang pig for which I can find no source; I have written to Zhiliang and Cari
I followed your advice in using "|" when I had more than one source.
Also, I added a new column V for comments and explanations that I hope are helpful. Included in this column are cases such as the one addressed by you in point 3 in your comment immediately above this one. There are a couple of cases where a comment in this column suggests an entry in the [matching sheet](https://docs.google.com/spreadsheets/d/1MxZrRYooKGS-1OHt75i_WR4y_uE_lW3yHCRyWAGOW3Q/edit#gid=2052501147). I did this because I feared that if I actually added the match I may have created a problem if you have already processed that page.
There may well be mistakes in what I have entered, so please contact me if anything seems a bit strange. 
I will send another comment as soon as I have completed the Meijiang pig entry.

**Comment by franknic** [comment]
Back again. Zhiliang has responded that Meijiang is actually Neijiang, which can be matched with Neijiang, China (Pig) VBO:0012825. I've added this as a comment in the "new" sheet.
So, that's all 641 done! (Apart from the inevitable errors !)

**Comment by franknic** [comment]
The breakdown of the 641 is:
557 matched to existing VBO entries, and 
84 matched to new VBO entries. Of the 84 new entries, Mason's dictionary is a key source for 55 entries. (The Mason encyclopedia was also a source for 45 of those 55 entries)

**Comment by katiermullen** [comment]
@franknic Thank you so much for all of your work on the LBO mapping. I am working on putting all of your work into a ROBOT template so that we can add it to VBO. I am sure more questions will arise, but one question so far. 

I see that you mapped 
LBO:0000790 Galiceño and LBO:0000791 Galician Pony to VBO:0011633 Galiceno, Mexico (Horse). This [source](https://breeds.okstate.edu/horses/) lists Galiceño and Galician Pony as separate breeds. Can you verify if they represent the same or different breeds?

**Comment by franknic** [comment]
Well spotted, Katie!
Having now checked my notes, it is evident that I have none for that entry, which means that I didn't consult Mason, which I should have done! He very clearly has them as two breeds:
1. Galiceño: (Mexico) / py; ri. / short criollo type in Mexico (orig. from Galician Pony), taken to USA to standardize / BS USA 1959
2. Galician Pony: (NW Spain) / m.ri.pa. / usu. chestnut, also sorrel, black or dappled; semi-feral / cf. Garrano / northern, central and southeastern types / orig. of Galiceño / HB 1994 / Sp. Faca galizana, Jaca gallega, Poney (or Poni) gallego / syn. Caballo gallego de monte, Faco pony / at one time combined with Asturian as Galician-Asturian (Sp. Poney galaico-asturiano or galaico-asturico)
So, we can match LBO:0000790 Galiceño to VBO:0011633 Galiceno, Mexico (Horse) (including the LBO synonym); and we need a new VBO (transboundary) breed for LBO:0000791 Galician Pony, with Oklahoma and Mason (both ISBNs) as sources.
A complication is that, as noted by Oklahoma and Mason, Galiceño is now well established in the USA, with its own breed society. This means that we really need a new VBO transboundary Galiceno (Horse) as a parent of VBO:0011633 Galiceno, Mexico (Horse), with Oklahoma and Mason ISBN:9781789241532 as sources, and, to be completely thorough, a new VBO breed country for Galiceno, United States of America (Horse), with Oklahoma and Mason ISBN:9781789241532 as sources, which will also have the new VBO transboundary Galiceno (Horse) as its parent.
I hope this is helpful.
