### ISSUE TITLE
VBO v2022-09-22

### ISSUE THREAD

**Issue by franknic** [monarch-initiative/vertebrate-breed-ontology#50]
It is a great pleasure to be able to start a new issue with this title!!
When trying to download the OWL file from the GitHub site (https://github.com/monarch-initiative/vertebrate-breed-ontology/blob/master/vbo.owl), we encountered an error message, but the download from OBO Foundry, which has a slightly different URL (https://raw.githubusercontent.com/monarch-initiative/vertebrate-breed-ontology/master/vbo.owl), worked fine.
We have been able to look around in Protege sufficiently to see that the weird characters are no longer there (!), but we would greatly appreciate a lesson on how to better use Protege, especially to show VBO to other people.
Also, Sabrina or Nicole: would you please add LeroyGregoire and Zhiliang and Cari (not sure of their GitHub ids) to this discussion.
We are very grateful for all the effort that has gone into getting us to this stage!!
Frank and Imke

**Comment by franknic** [comment]
Cari's and Zhiliang's GitHub ids are caripark and zhilianghu, respectively.

**Comment by matentzn** [comment]
How did you try to download it? With protege? By hand through the browser? If you go to the GitHub site that "does not work", you can use the "raw" or the "Download" button to download the file!

**Comment by franknic** [comment]
Yes, with Protege. I've just tried your suggestion of downloading the OWL file from GitHub and then opening it in Protege, and that worked fine; thank you! So, the file itself is fine. But I tried again to open that same OWL file via Protege's "Open from URL" tool and that failed again as before, whereas that same tool worked fine in opening the file from the OBO Foundry. This suggests a problem with the URL, but I may be doing something stupid. I've attached a screenshot of the error message.
![Screenshot (40)](https://user-images.githubusercontent.com/79228708/191900451-9f30a032-fdd5-4a51-a6f0-9bf42c1670ef.png)

**Comment by matentzn** [comment]
Yes this url is just not the ontology! It looks like it, but it is, in fact, a link to a website on GitHub!

**Comment by franknic** [comment]
Thanks, Nico! Yes, it's the URL for the actual VBO OWL file on GitHub

**Comment by matentzn** [comment]
When we are in OBO land, we should _never_ use URLs to refer to ontologies. 

https://github.com/monarch-initiative/vertebrate-breed-ontology/blob/master/vbo.owl looks like it is an Ontology URL, but it is not - if you put it in the browser, it will point to a website _about the ontology_ (from which there are other links you can use to download it). So the URL is a bit deceptive because it ends with "vbo.owl".

In OBO land we should not be using URLs _ever_ we should be using PURL (persistent URLs). The persistent URL of VBO is:

http://purl.obolibrary.org/obo/vbo.owl


If VBO changes in the future, for example, it is moved to a different repository or something, this PURL will continue to work! All users of VBO should use that - and nothing else (neither raw.github nor any other). 

Hope that makes sense!

**Comment by franknic** [comment]
Thank you very much, Nico! Yes, that does make sense, and is very helpful to someone like me. It seems that the "Open from URL" tool in Protege could do with a "health" warning!

**Comment by matentzn** [comment]
Yes!! :)

**Comment by franknic** [comment]
Many thanks for this conversation, Nico, which I have greatly enjoyed and which has been very informative for me.

**Comment by sabrinatoro** [comment]
This issue can be closed
