### ISSUE TITLE
review possible typos in original templates

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#7]
In this document:  https://docs.google.com/spreadsheets/d/1KKJWPCY5jR72IukfX9OOyHK9L8TH2Qs4hcmgT-0kR6U/edit?usp=sharing

- "NCBI ROBOT 2:transboundary" sheet
-- lines 55 and 56 (VBO:0000089-90): are these duplicated? which one is correct (note to self, check the ID in the other sheet accordingly)
-- lines 81 and 82 (VBO:0000115-116): are these duplicated? which one is correct (note to self, check the ID in the other sheet accordingly)
-- lines 116-118(VBO:0000150; VBO:0000151; VBO:0000152) : are these duplicated? 

- "NCBI ROBOT 3:breed" sheet
-- line 4727 colB (VBO:0006447): should it be "Sussex" (instead of suseks)
-- line 4626 colB (VBO:0006346): the name of this breed is "Rhode Island White ISA Hendrix Genetics" but the transboundary name in "Rhode Island Red". Is this correct or is this a typo? If it is a type, is it same as line 4625 (VBO:0006345)?

**Comment by sabrinatoro** [comment]
@franknic @ImkeTammen 
Please review the lines above, and please let me know when you have reviewed them. 
You can either update the main document directly, or you can add here what changes need to be made, and I will update the document myself. 
Thank you!

**Comment by franknic** [comment]
Thank you Sabrina. I'll address your questions above.
"NCBI ROBOT 2:transboundary" sheet
lines 55 and 56 (VBO:0000089-90): are these duplicated? which one is correct
Yes, 55 and 56 are duplicates. The correct one is 56, i.e. the one with the hyphen is correct. When fixing this, please ensure that all the information associated with the incorrect transboundary name "Aberdeen Angus" is associated with the correct name, namely "Aberdeen-Angus". 
lines 81 and 82 (VBO:0000115-116): are these duplicated? which one is correct 
Yes, these are duplicates. The correct one is 81, i.e. the one without the hyphen. As above, please ensure that the information associated with 82 is associated with 81.
lines 116-118(VBO:0000150; VBO:0000151; VBO:0000152) : are these duplicated?
Yes, these are duplicates. The correct one is 117, i.e. Blonde d'Aquitaine. As above, please ensure that the information associated with 116 and 118 is associated with 117.
Others I spotted while scanning the whole file:
51 should really be "water buffalo" rather than "water Buffalo". There was a row for "water buffalo" but this has been discarded. So, the request is to pool together all the information for "water Buffalo" and "water buffalo" and call the entry "water buffalo"
147 (CrÃ©ole) is a duplicate of 148 (Creole); retain 148 and discard 147, after re-associating the other 147 information
206 is a duplicate of 205; retain 205 and discard 206, after re-associating the other 206 information
1283 is a duplicate of 1282; retain 1282 (Barbados Black Belly) and discard 1283, after re-associating the other 1283 information
1373 is a duplicate of 1372 (Est à laine Mérino): retain 1372 and discard 1373, after re-associating the other 1373 information 
1425 is a duplicate of 1424: retain 1424 and discard 1425, after re-associating the other 1425 information
1583 should be "Spælsau"; and 1584 is a duplicate of 1583; retain 1583 and discard 1584, after re-associating the other 1584 information

"NCBI ROBOT 3:breed" sheet
4727: Yes, "suseks" should be "Sussex"
4626: I can't answer that question !! I'll have to check with the DADIS people. Is it feasible to leave it as it is now, and (if necessary) change it later?

I hope I've addressed everything!

**Comment by sabrinatoro** [comment]
NCBI ROBOT 2: transboundary
- (line 55) VBO:0000089 was removed ; it was not used in the Breed sheet
- (line 82) VBO:0000116 was removed ; VBO:0002279 record in the Breed sheet was updated accordingly
- (line 116) VBO:0000150 was removed, VBO:0002420 record in the Breed sheet was updated accordingly
-  (line 118) VBO:0000152 was removed,  28 records in the Breed sheet were updated accordingly
- (mine 51) VBO:0000085 name updated; 2 records in the Breed sheet were updated accordingly
-  (line 147) VBO:0000181 was removed,  VBO:0002793 record in the Breed sheet was updated accordingly
-  (line 206) VBO:0000240 was removed,  VBO:0003308 record in the Breed sheet was updated accordingly
- (line 1283) VBO:0001317 was removed,  VBO:0014215 record in the Breed sheet was updated accordingly
- (line 1373) VBO:0001407 was removed, VBO:0014594 record in the Breed sheet was updated accordingly
-  (line 1425) VBO:0001459 was removed,  VBO:0014757 record in the Breed sheet was updated accordingly
-  (line 1584) VBO:0001618 was removed,  VBO:0015290 and VBO:0015291 records in the Breed sheet was updated accordingly

"NCBI ROBOT 3:breed" sheet
-  VBO:0006447 label name was updated
-  line 4626, VBO:0006346 : kept as it currently is. (@franknic : yes, we can definitely change it later if we need too). 

Note: I deleted the duplicated line from the spreadsheet. Therefore the line numbers will not match the numbers in this issue anymore.
